# Generated by Django 3.0.8 on 2020-07-25 14:37

from django.db import migrations, models
import django.db.models.deletion
import passport.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Passport',
            fields=[
                ('passport_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('passport_holder_name', models.CharField(max_length=45)),
                ('passport_access_token', models.CharField(max_length=655)),
                ('passport_address', models.CharField(max_length=70)),
                ('passport_created_on', models.DateTimeField(auto_now_add=True)),
                ('passport_updated_on', models.DateTimeField(auto_now_add=True)),
                ('passport_is_verified', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ExpiredPassport',
            fields=[
                ('passport', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='passport.Passport')),
            ],
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('linked_passport', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='passport.Passport')),
                ('income', models.IntegerField(default=0)),
                ('money_left', models.IntegerField(default=models.IntegerField(default=0))),
                ('savings', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('linked_passport', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='passport.Passport')),
                ('plan', models.CharField(max_length=10)),
                ('validity', models.DateTimeField(default=passport.models.set_default_validity)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('profile_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=60)),
                ('last_name', models.CharField(max_length=60)),
                ('color_accent', models.CharField(choices=[('bg', 'Blue and Green'), ('bg2', 'Blue and Violet'), ('bg3', 'Pure Blue'), ('bg4', 'Yellow and Violet'), ('bg5', 'Red and Pink')], default='blue', max_length=10)),
                ('profile_picture', models.FileField(upload_to=passport.models.get_upload_path)),
                ('linked_passport', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='passport.Passport')),
            ],
        ),
    ]
