# Generated by Django 3.0.8 on 2020-07-19 16:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Passport',
            fields=[
                ('passport_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('passport_holder_name', models.CharField(max_length=45)),
                ('passport_access_token', models.CharField(max_length=655)),
                ('passport_address', models.CharField(max_length=70)),
                ('passport_created_on', models.DateTimeField(auto_now_add=True)),
                ('passport_updated_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
